name: legendary
description: A client for interacting with Legendary Epic Games Launcher type-safely.
version: 0.1.1
repository: https://github.com/aitor-gomila/legendary-dart

environment:
  sdk: ^3.0.0

dependencies:
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
